
require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe', 'before']
  
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: separator

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/CharacterLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/MultilineBlockChain:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: [x, y, p, i, n, op]

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
